#!/bin/sh

[ "$ACTION" == "add" ] || exit 1
[ -n "$INTERFACE" ] || exit 2

case "$ACTION" in
	add)
		case "$INTERFACE" in
			br-lanap|br-lanrelay|br-lan)
				ifconfig $INTERFACE:1 6.6.6.6 netmask 255.255.255.0
			;;
			*)
			;;
		esac
	;;
	*)
	;;
esac

exit 0
