name: Auto-Build

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_NAME: MT3600BE-AUTO
      WRT_CONFIG: Config/MT3600BE-MINIMAL.txt
      WRT_GENERAL: Config/GENERAL-FULL.txt
      WRT_IP: 192.168.8.1
      WRT_THEME: argon
      WRT_RELEASE: false
